# Deprecated ?
#version: '3.8'

services:

  mariadb:
    env_file: .env
    build: requirements/mariadb
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - docker_network

  wordpress:
    build: requirements/wordpress
    volumes:
      - wordpress_volume:/var/www/wordpress
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - docker_network

  nginx:
    build: requirements/nginx
    # Only service to expose a port to the outside
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - docker_network
    #restart: on-failure
    
  redis:
    build: requirements/bonus/redis
    # Only service to expose a port to the outside
    networks:
      - docker_network
    #restart: on-failure

networks:
  docker_network:
    driver: bridge

# We are using "named" bind mounts
volumes:
  wordpress_volume:
    driver_opts:
      type: none
      device: /home/tpouget/data/wordpress
      o: bind
  mariadb_volume:
    driver_opts:
      type: none
      device: /home/tpouget/data/mariadb
      o: bind
