# Deprecated ?
#version: '3.8'

services:

  mariadb:
    #container_name: mariadb
    env_file: .env
    build: 
      context : requirements/mariadb
      args:
      - MYSQL_DATABASE_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_DATABASE_PREFIX
    #image: mariadb:inception
    volumes:
      - /home/tpouget/data/mariadb:/var/lib/mysql
      #- mariadb_volume:/var/lib/mysql
    #networks:
    #  - docker_network
    #restart: on-failure

  wordpress:
    #container_name: wordpress
    build: requirements/wordpress
    #image: wordpress:inception
    volumes:
      - wordpress_volume:/var/www/wordpress
    env_file: .env
    depends_on:
      - mariadb
    #networks:
    #  - docker_network
    #restart: on-failure

  nginx:
    #container_name: nginx
    build: requirements/nginx
    #image: nginx:inception
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/wordpress
    depends_on:
      - wordpress
    #networks:
    #  - docker_network
    #restart: on-failure

#networks:
#  docker_network:
#    driver: bridge

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/tpouget/data/wordpress
      o: bind
  #mariadb_volume:
  #  driver: local
  #  driver_opts:
  #    type: none
  #    device: /home/tpouget/data/mariadb
  #    o: bind
