# Deprecated ?
#version: '3.8'

services:

  mariadb:
    build: requirements/mariadb
    env_file: .env
    networks:
      - docker_network
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart: on-failure

  wordpress:
    build: requirements/wordpress
    depends_on:
      - mariadb
    depends_on:
      - mariadb
    env_file: .env
    environment:
      - BONUS=${BONUS:-no}
    networks:
      - docker_network
    volumes:
      - wordpress_volume:/var/www/wordpress
    restart: on-failure

  nginx:
    build: requirements/nginx
    # Only service to expose a port to the outside
    depends_on:
      - wordpress
    networks:
      - docker_network
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/wordpress
    restart: on-failure
    
  redis:
    build: requirements/bonus/redis
    # Only service to expose a port to the outside
    networks:
      - docker_network
    profiles:
      - bonus
    restart: on-failure
    
networks:
  docker_network:
    driver: bridge

# We are using "named" bind mounts
volumes:
  wordpress_volume:
    driver_opts:
      type: none
      device: /home/tpouget/data/wordpress
      o: bind
  mariadb_volume:
    driver_opts:
      type: none
      device: /home/tpouget/data/mariadb
      o: bind
